GET http://localhost:3001/api/products/5fa548115d2c8b0e348e5331

###

GET http://localhost:3001/api/products

###

DELETE http://localhost:3001/api/products/5fa9b77e5ca61107e4322d70

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "",
  "name": "",
  "password": ""
}

###

POST http://localhost:3001/api/products
Content-Type: application/json

{
  "name": "juup",
  "price": 5,
  "weight": 1.6,
  "userId": "6028fb798215333ae488f6d7"
}

###

PUT http://localhost:3001/api/products/5fa55123fecbf329d4aa8bea
Content-Type: application/json

{
  "price": 1.7,
  "weight": 0.5
}

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "",
  "password": ""
}

###

POST http://localhost:3001/api/products
Content-type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9eyJ1c2VybmFtZSI6Imp1aGF4aXMiLCJpZCI6IjVmMjE2MzU5NThlMDgwMzkyNDA0OWJjMiIsImlhdCI6MTU5NjAyMzY0OH0.fh3UWFRC2FPTDwcTW4UH3vAmUUodpU__hXHTHRcJbJE

{
  "name": "juup",
  "price": 5,
  "weight": 1.6
}