GET http://localhost:3001/api/products/5fa548115d2c8b0e348e5331

###

GET http://localhost:3001/api/products

###

DELETE http://localhost:3001/api/products/5fa6cf87b338720ba491c249

###

POST http://localhost:3001/api/products
Content-Type: application/json

{
  "name": "maltsu3",
  "price": 5,
  "weight": 1.6
}

###

PUT http://localhost:3001/api/products/5fa55123fecbf329d4aa8bea
Content-Type: application/json

{
  "price": 1.7,
  "weight": 0.5
}

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "juha",
  "password": "salasana"
}